### ISSUE TITLE
manual testcase is not visible on creating issues

### ISSUE THREAD

**Issue by schoenfr** [Pepperrs/red_jenkins#33] opened 2015-04-08 17:59 UTC
on the live system, we found this issue.
Reproduction: Choose any project, create a manual test case, go to "new issue". There is no testcase assignable there.
Maybe this is a bug with multiple projects (or maybe it is the underscore in the project name). I dont know.

**Comment by Pepperrs** [comment] 2015-04-09 15:24
the system is probably not correctly migrated. Will follow on when I either manage to reproduce the issue on my system or revisit your installation.

**Comment by Pepperrs** [comment] 2015-04-09 16:23
Another symptom of probably the same error: Issue#edit does not show options for testcases.
Probably javascript or database related.

Also these features are functional on a bitnami style installation. Will test with a manual installation.

**Comment by Pepperrs** [comment] 2015-04-09 16:29
affore mentioned issue#edit error could be due to my account having reporter status. however when i edit an issue (which doenst show testcase related information) it breaks the redmine. this only happens on swtp redmine.

**Comment by Pepperrs** [comment] 2015-04-10 11:10
path was hardcoded. is now fixed

**Closed by Pepperrs** 2015-04-10 11:10 UTC
